### ISSUE TITLE
how to detect novel class with AE-WTN?

### ISSUE THREAD

**Issue by XiaoJiNu** [xternalz/AE-WTN#1]
Hi, your work is so great! I have read your paper but I don't understand that how you can detect novel class with AE-WTN? 
What's the process of regression and classification of novel class?

**Comment by xternalz** [comment]
Hi @XiaoJiNu, thanks for your interest. The novel classes are detected using the classification weights transformed from large-scale classification network (this was trained on novel classes but not the detection network) using AE-WTN. The box regression part is class-agnostic, meaning that it only outputs 1x4 regression values to be used for all classes including the novel ones.

**Comment by XiaoJiNu** [comment]
@xternalz thanks for your reply, I understood.

**Comment by pjh4993** [comment]
Hi, I'm trying to use your work for my custom dataset. While using your model I wonder is box regression is truly trained to class agnostic way to the whole object. Isn't it more precise to say box regression is trained to be class agnostic to the training dataset? I'm quite confused about how regression can be trained class agnostic to the novel dataset while didn't seen at training time.

**Comment by xternalz** [comment]
When a detector is trained to perform box regression for many (seen) object categories in a class agnostic fashion, its box regression network can somehow generalize to unseen object categories in another dataset. This is related to learning generic objectness. Several works have also shown that class-agnostic box regression generalizes well to unseen object categories or object categories which do not have box annotations:
- What leads to generalization of object proposals?. ArXiv 2020.
- R-FCN-3000 at 30FPS: Decoupling Detection and Classification. CVPR 2018.

We never claimed anything about the box regression being class-agnostic to novel categories and/or datasets.
