### ISSUE TITLE
How to train the WTN model using the released code?

### ISSUE THREAD

**Issue by HarveyGuo960817** [xternalz/AE-WTN#2]
Hello, I read your paper and enjoy your proposed method solving partial-supervised object detection. Reading your released code, I cannot find the code about AE-WTN and the pre-trained CLN. I wonder to consult that how to train the WTN mode using the released code?

**Comment by xternalz** [comment]
This codebase supports AE-WTN training by default. The related code is found here:
https://github.com/xternalz/AE-WTN/blob/master/maskrcnn_benchmark/modeling/roi_heads/box_head/roi_box_predictors.py#L56-L112
